include: package:effective_dart/analysis_options.yaml

# analyzer:
  # exclude: [build/**]
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    todo: ignore

linter:
  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    prefer_relative_imports: false
    