name: engine
description: Factorymatics game engine library
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
#  uuid: ^2.2.0
  uuid: ^3.0.6
  tuple: ^2.0.0
  mockito: ^5.3.0
  build_runner: ^2.2.0
  logging: ^1.0.2
  intl: ^0.17.0
  args: ^2.3.1
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  effective_dart: ^1.3.2
  test: ^1.21.4
