name: factorymatics
description: An engine builder game.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  engine:
    path: ../engine
  server:
    path: ../server
  tuple: ^2.0.0-nullsafety.0
  get_it: ^7.2.0

  cupertino_icons: ^1.0.2
  flutter_vector_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  #integration_test: ^1.0.2+3
  flutter_driver:
    sdk: flutter  

  effective_dart: ^1.0.0
  mockito: any

flutter:

  uses-material-design: true
